
export enum ApiResponseCode {

  SAVE_SUCCESS= 'SAVE_SUCCESS',
  UPDATE_SUCCESS= 'UPDATE_SUCCESS',
  DELETE_SUCCESS= 'DELETE_SUCCESS',
  FETCH_DATA_SUCCESS= 'FETCH_DATA_SUCCESS',
  WRONG_CREDENTIALS= 'WRONG_CREDENTIALS',
  UNAUTHORIZED= 'UNAUTHORIZED',
  ACCESS_DENIED= 'ACCESS_DENIED',
  NOT_FOUND= 'NOT_FOUND',
  BAD_REQUEST= 'BAD_REQUEST',
  CONSTRAINT_VIOLATION_ERROR= 'CONSTRAINT_VIOLATION_ERROR',
  DUPLICATE_ENTITY= 'DUPLICATE_ENTITY',

  ERROR= 'ERROR',

  NONE= 'NONE',

}
